In [2]:
import pandas as pd
df = pd.read_csv('data_for_large_scale.csv')

In [3]:
df.head()

Feature-1  Feature-2  Feature-3  Feature-4  Feature-5  Feature-6  \
0     -1.580     1.0500      1.060     -0.440      0.451    -0.0348   
1     -0.832    -0.8660     -1.340      0.138      1.180     0.7330   
2     -0.237     2.0900     -3.930      0.296      0.352    -0.5010   
3     -1.170    -1.1300     -1.090      1.120      0.312     0.1830   
4      0.260    -0.0273      0.925     -1.150     -1.390     0.0251   

   Feature-7  Feature-8  Feature-9  Feature-10  Target  
0      0.643     0.2650      0.268      -0.851    84.7  
1     -1.410     0.1350     -0.088      -1.550  -211.0  
2      0.961    -0.0287      1.820       0.938   -96.9  
3      0.448    -0.8190     -1.010      -1.080  -152.0  
4      0.627     0.0950     -0.280      -0.848   -57.7

In [4]:
L = list(df.columns)
L.remove("Target")
X = df[L]
Y = df["Target"]

In [12]:
X_list = X.values.tolist()
Y_list = Y.tolist()

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X_list,Y_list,test_size=0.3,random_state=10)

In [26]:
import numpy as np
X_train = np.array(X_train)
X_test = np.array(X_test)

In [27]:
X_train = X_train.reshape(-1,90,X_train.shape[1])

In [28]:
Y_train = np.array(Y_train)
Y_test = np.array(Y_test)

In [30]:
Y_train = Y_train.reshape(-1,90,1)

In [31]:
from sklearn.linear_model import SGDRegressor
sg = SGDRegressor(random_state=10)

for i in range(90):
    f = X_train[i]
    f1 = Y_train[i]
    sg.partial_fit(f,f1)

/home/om/Documents/Codes/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/om/Documents/Codes/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/om/Documents/Codes/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/om/Documents/Codes/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d

In [33]:
print(sg.intercept_)

[0.0127488]


In [59]:
df = pd.read_csv("3D_spatial_network.csv",chunksize=20000,iterator=True)

In [46]:
val = 0
for i in df:
    val += i.shape[0]
print(val)

434873


In [60]:
from sklearn.linear_model import SGDRegressor
import pandas as pd
from sklearn.preprocessing import StandardScaler

sg = SGDRegressor(random_state=10)
sc = StandardScaler()

for chunk in df:
    chunk = chunk.dropna()
    X = chunk.iloc[:, :-1]
    sc.partial_fit(X)
    X = sc.transform(X)
    y = chunk.iloc[:, -1]
    y = pd.to_numeric(y, errors='coerce')
    sg.partial_fit(X, y)
    print(sg.coef_)


[ 1.97488393  4.90212385 -3.50180936]
[ 3.49805201  0.3375425  -0.98757252]
[ 5.99129947  2.08265507 -0.4435826 ]
[ 3.42607209  4.11925225 -4.03197196]
[ 1.42280183  1.1089138  -0.7591445 ]
[ 0.87345066  4.0826797  -5.58786032]
[-0.16412588  4.61899301 -5.16555598]
[ 3.21666323  4.53260206 -4.56591173]
[ 3.30391999  5.42920198 -5.54858025]
[ 4.21689489  3.62973598 -4.21769064]
[ 2.5858368  -0.91256733  0.50572045]
[ 0.5376402   3.71574028 -4.24690532]
[ 3.06902888  3.60656971 -4.75099768]
[ 2.20831686  3.86873596 -3.84302602]
[ 1.03714796 -1.43170493 -2.16750385]
[ 0.03220156 -0.66037418 -3.42030796]
[ 0.54940871  1.23937936 -2.61574311]
[ 2.62694761  2.77537509 -2.09696084]
[-0.62067653  4.73618953 -5.67211573]
[ 3.18163234  3.17139089 -3.20619567]
[-0.01889937  0.44146039 -2.66295055]
[ 0.28232131  3.1785343  -4.8238153 ]


In [43]:
print(sg)

SGDRegressor(random_state=10)


In [61]:
from sklearn.datasets import load_iris
data = load_iris()
X = data.data
Y = data.target

In [62]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=10)

In [63]:
from sklearn.preprocessing import Normalizer
nz = Normalizer()
nz.fit(X_train)
X_train = nz.transform(X_train)
X_test = nz.transform(X_test)

In [66]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,Y_train)
print(accuracy_score(Y_test,knn.predict(X_test)))

0.9666666666666667


In [67]:
from sklearn.metrics import f1_score
print(f1_score(Y_test,knn.predict(X_test),average='weighted'))

0.9671111111111111
